### ISSUE TITLE
iOS SDK 需要升级以便适配 iOS 14.5 新规

### ISSUE THREAD

**Issue by wenxiangjiang** [gstory0404/flutter_unionad#10]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/10527100/107144246-f146bd80-6974-11eb-834c-850e8e177903.png">

**Comment by zhangruiyu** [comment]
亲爱的合作伙伴：

      苹果预计将更新iOS 14.5版本，因iOS功能调整，届时将会对ios广告收入造成重大影响。为保障开发者的收益，我们已发布了专门适配iOS 14.5版本的SDK（3423以上的版本），请务必不晚于2月20日之前将SDK更新至3423及以上版本，避免您的收入遭受严重损失！！！

**Comment by zhangruiyu** [comment]
确实需要老哥给升级下了

**Comment by wenxiangjiang** [comment]
看看过完年作者是否有时间 @zhangruiyu

**Comment by gstory0404** [comment]
过年回家没带电脑 暂时更新不了 如果有小伙伴有做了这个升级 可以pr一下

**Comment by zhangruiyu** [comment]
emmmm不造咋改啊..

**Comment by zhangruiyu** [comment]
已经提了pr, 好像就需要更新下版本就行了

**Comment by wenxiangjiang** [comment]
@zhangruiyu 不只是更新 SDK 的版本号，还需要添加一个名为 `requestTrackingAuthorization` 的方法以便请求 `ATT` 授权，如果可以的话还可以添加一个获取当前 `ATT` 授权状态的方法。

**Comment by gstory0404** [comment]
已经发布了最新版本  sdk 安卓、ios都更新到最新的了，ATT权限申请已集成
