### ISSUE TITLE
splashAdView 预下载的widget如何使用

### ISSUE THREAD

**Issue by xue9122** [gstory0404/flutter_unionad#100]
splashAdView设置adLoadType为PRELOAD,进行预加载

FlutterUnionad.splashAdView(
                ...
                //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
                adLoadType: FlutterUnionadLoadType.PRELOAD,
...);

两个问题：
1.什么时候记性预加载，是启动app的时候吗？
2.怎么判断预加载成功了，怎么使用成功预加载的物料呢？

**Comment by gstory0404** [comment]
目前仅激励广告 插屏广告支持预加载
