### ISSUE TITLE
渲染穿山甲信息流广告时闪退

### ISSUE THREAD

**Issue by WanGe2000** [gstory0404/flutter_unionad#101]
### 描述
渲染穿山甲信息流广告时闪退

### 设备版本
本地 flutter 版本：
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (9 weeks ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
设备版本：
iPhone12  ios 16.5

### 日志
flutter_unionad/NativeAdView.swift:48: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread#1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001c1338a3c libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1c1338a3c <+0>: ret
libswiftCore.dylib`:
    0x1c1338a40 <+0>: b      0x1c1338a3c               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1c1338a44 <+0>: adrp   x8, 366325
    0x1c1338a48 <+4>: ldrb   w0, [x8, #0x994]

**Comment by gstory0404** [comment]
插件版本号

**Comment by gstory0404** [comment]
> > 插件版本号
> 
> 1.3.22

更新最新版本试试

**Comment by WanGe2000** [comment]
pub.dev 上 flutter_unionad 最新就是 1.3.22，还是说你指的是穿山甲的 sdk 版本吗？

**Comment by WanGe2000** [comment]
> > > 插件版本号
> > 
> > 
> > 1.3.22
> 
> 更新最新版本试试

pub.dev 上 flutter_unionad 最新就是 1.3.22，还是说你指的是穿山甲的 sdk 版本吗？

**Comment by gstory0404** [comment]
最新1.3.23国内镜像可能没有同步吧 引用git源试试

**Comment by WanGe2000** [comment]
> 最新1.3.23国内镜像可能没有同步吧 引用git源试试

好的，我明天试下再给你反馈，谢谢

**Comment by WanGe2000** [comment]
> > > 插件版本号
> > 
> > 
> > 1.3.22
> 
> 更新最新版本试试

可以了，最新版本不会闪退，多谢
