### ISSUE TITLE
如何支持’获取展示后广告信息事例‘

### ISSUE THREAD

**Issue by J-Yaleen** [gstory0404/flutter_unionad#102]
### 描述
穿山甲有个获取展示后广告信息事例的方法
希望支持这个方法，或者有什么临时的方法吗？
![image](https://github.com/gstory0404/flutter_unionad/assets/107242550/2c64216f-6165-4426-9a8a-dd6899d6306e)

### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
插件不支持，fork代码加入

**Comment by gstory0404** [comment]
这些回调 用该都是弃用状态吧
