### ISSUE TITLE
开屏广告隐藏跳过设置隐藏不管用

### ISSUE THREAD

**Issue by 1052441207** [gstory0404/flutter_unionad#103]
### 描述
> hideSkip设置为true，但是开屏广告的跳过按钮还是存在。
![Screenshot_2023-08-26-22-31-40-300_com yiye paikebao](https://github.com/gstory0404/flutter_unionad/assets/10349079/a59d8441-5193-4cb4-87af-3f4fd479f305)

**Comment by gstory0404** [comment]
本身就不允许影藏

**Comment by 1052441207** [comment]
好的，谢谢
