### ISSUE TITLE
banner广告加载失败 data analysis error

### ISSUE THREAD

**Issue by dboylx** [gstory0404/flutter_unionad#104]
### 描述
> 异常/需求具体描述
把例子放到工程里面，初始化是成功的（sdk初始化 true），但点击例子中的广告控制台报这个错误：
banner广告加载失败 data analysis error

### 设备版本
> 本地flutter版本、设备型号版本
flutter : 3.13.9
dart :  3.1.5

### 插件版本
> 插件版本号
1.3.26

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
@dboylx 其他广告是否也无法加载

**Comment by lzz29** [comment]
我也遇到同样的问题，目前是banner广告会提示这个 data analysis error
信息流的话正常 但是图片有时候会加载不出来 感觉是本地开发环境的问题

**Comment by gstory0404** [comment]
开启http了吗，有的时候因为返回素材是http的 可能导致无法加载图片 @lzz29

**Comment by cijianzy** [comment]
}, origin_error_code=10002000, extra_reason=两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8, NSLocalizedDescription=data analysis error})


提示这个。

**Comment by gstory0404** [comment]
banner使用模版渲染代码位

> }, origin_error_code=10002000, extra_reason=两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8, NSLocalizedDescription=data analysis error})
> 
> 提示这个。
