### ISSUE TITLE
如何去除广告内容半透明蒙版？

### ISSUE THREAD

**Issue by wangzy2u** [gstory0404/flutter_unionad#105]
### 描述
> 异常/需求具体描述

### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
具体哪个？

**Comment by wangzy2u** [comment]
![WechatIMG1](https://github.com/gstory0404/flutter_unionad/assets/13634637/886c32fe-f4f3-4f7a-a816-4ad31f694403)
这种，信息流广告上展示的蒙层

**Comment by gstory0404** [comment]
原生SDK内置的图层 暂时没有方法影藏

**Comment by wangzy2u** [comment]
好的
