### ISSUE TITLE
SDK版本可以升级一下吗

### ISSUE THREAD

**Issue by sing1** [gstory0404/flutter_unionad#106]
目前Android的SDK最新版本为6.1.0.4，IOS的为6.2.0.0，可否升级一下？

**Comment by sing1** [comment]
banner广告加载失败 reason: 0  message: 两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8

**Comment by gstory0404** [comment]
新版本改动比较大，聚合广告与普通广告sdk合并了，插件逻辑需要调整，需要等几天空闲了 才能重新调整一下再更新

**Comment by gstory0404** [comment]
@sing1 已更新[2.0.0](https://github.com/gstory0404/flutter_unionad/blob/master/CHANGELOG.md)
