### ISSUE TITLE
插件版本号 2.0.1 编译iOS项目报错

### ISSUE THREAD

**Issue by MiaoShichang** [gstory0404/flutter_unionad#109]
### 描述
xcode 报错

### 设备版本
> 本地flutter版本、设备型号版本
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Users/miaoxinhai/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

### 插件版本
> 插件版本号 2.0.1

### 日志
> 详细的log日志或者截图录屏
```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           31.5s
Failed to build iOS app
Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:13:38

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAdDelegate' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:36:30

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:37:63

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:43:65

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:50:71

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:54:55

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:61:63

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:68:64

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:71:66

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:75:67

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:82:74

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:86:68

Swift Compiler Error (Xcode): Cannot find type 'BUFullscreenVideoAd' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:93:63

Swift Compiler Error (Xcode): Cannot find type 'BUFullScreenVideoAdType' in scope
/Users/mmm/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-2.0.1/ios/Classes/fullscreenvideoAd/FullScreenVideoAd.swift:93:112

Uncategorized (Xcode): Command SwiftEmitModule failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

**Comment by gstory0404** [comment]
清理缓存 到ios目录下pod update

**Comment by MiaoShichang** [comment]
> 清理缓存 到ios目录下pod update

pod update 和 pod install 都不管用

===================
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 27 total pods installed.


=====================
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 27 total pods installed.

**Comment by MiaoShichang** [comment]
> 清理缓存 到ios目录下pod update

pod update 和 pod install 都不管用

===================
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 27 total pods installed.


=====================
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 27 total pods installed.

**Comment by gstory0404** [comment]
flutter缓存也清一下

**Comment by MiaoShichang** [comment]
> flutter缓存也清一下

<img width="413" alt="image" src="https://github.com/gstory0404/flutter_unionad/assets/14245525/722bf396-81cb-4ff3-b7ea-0c44e29b66a0">


Ads-CN-Beta/BUAdSDK 中缺少BUFullscreenVideoAd头文件，造成编译加载失败，

**Comment by gstory0404** [comment]
这个广告新版本插件中已经不用了，用新模板插屏全屏广告

**Comment by MiaoShichang** [comment]
> 这个广告新版本插件中已经不用了，用新模板插屏全屏广告

我没有使用，是你的插件中在使用

<img width="1132" alt="image" src="https://github.com/gstory0404/flutter_unionad/assets/14245525/30f318f1-accb-486e-9c4a-9fd483fd0cdf">

**Comment by gstory0404** [comment]
```
flutter_unionad:
  git:
     url: https://github.com/gstory0404/flutter_unionad.git
     ref: 7501452df8f767728be4ca0cabbebc64aed53d2c
```
xcode中删除代码 AS中未同步删除导致，暂时使用github引用吧，这边网络有问题上传不了

**Comment by MiaoShichang** [comment]
插屏广告添加了监听，需要在合适的时机移除监听吗？

<img width="881" alt="image" src="https://github.com/gstory0404/flutter_unionad/assets/14245525/65dc962f-5b3b-4a03-8eff-4ec7ff43024b">

**Comment by gstory0404** [comment]
这个需要在自己的业务中判断或者页面销毁时调用delete方法释放监听
