### ISSUE TITLE
自渲染信息流广告： 已回收，不再提供创建（仅支持历史创建代码位）

### ISSUE THREAD

**Issue by MarioMuYao** [gstory0404/flutter_unionad#114]
自渲染信息流广告： 已回收，不再提供创建（仅支持历史创建代码位）

能否支持模版信息流广告
mTTAdNative.loadNativeExpressAd(adSlot, new TTAdNative.NativeExpressAdListener() {

**Comment by gstory0404** [comment]
官方现在把原穿山甲与gromore广告合并了，文档也是gromore的，推荐使用gromore来创建广告
