### ISSUE TITLE
打包会报resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by qingfeilin** [gstory0404/flutter_unionad#117]
### 描述
> flutter run的时候真机调试是正常的，但是打包运行flutter build apk时会报resource android:attr/lStar not found.

### 设备版本
> ![image](https://github.com/user-attachments/assets/18f7ac00-e5fc-48d6-9cbe-cf222272013b)

### 日志
> 详细的log日志或者截图录屏
![image](https://github.com/user-attachments/assets/7adc6247-580d-4d30-8511-85fe9a503432)

**Comment by qingfeilin** [comment]
* What went wrong:
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
   > Android resource linking failed
     ERROR:G:\codeSpace\workspace\flutter_20240816\flutter_application_1\build\flutter_unionad\intermediates\merged_res\release\values\values.xml:2727: AAPT: error: resource android:attr/lStar not      ERROR:G:\codeSpace\workspace\flutter_20240816\flutter_application_1\build\flutter_unionad\intermediates\merged_res\release\values\values.xml:2727: AAPT: error: resource android:attr/lStar not found.

**Comment by qingfeilin** [comment]
* What went wrong:
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
   > Android resource linking failed
     ERROR:G:\codeSpace\workspace\flutter_20240816\flutter_application_1\build\flutter_unionad\intermediates\merged_res\release\values\values.xml:2727: AAPT: error: resource android:attr/lStar not      ERROR:G:\codeSpace\workspace\flutter_20240816\flutter_application_1\build\flutter_unionad\intermediates\merged_res\release\values\values.xml:2727: AAPT: error: resource android:attr/lStar not found.

**Comment by gstory0404** [comment]
https://github.com/gstory0404/flutter_unionad/blob/master/android/build.gradle
查看build中库与本地项目 版本号的差异

**Comment by qingfeilin** [comment]
> https://github.com/gstory0404/flutter_unionad/blob/master/android/build.gradle 查看build中库与本地项目版本号的差异

当前这个版本安卓sdk版本要用34的打包才可以
