### ISSUE TITLE
flutter_app/build/flutter_unionad/intermediates/merged_res/release/values/values.xml:2727: AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by dalingng** [gstory0404/flutter_unionad#118]
### 描述
> 异常/需求具体描述

### 设备版本
> 本地flutter版本、设备型号版本
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (4 周前) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

### 插件版本
> 插件版本号
flutter_unionad: ^2.0.8
### 日志
> 详细的log日志或者截图录屏
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/dng/work/control-cluster/flutter_app/build/flutter_unionad/intermediates/merged_res/release/values/values.xml:2727: AAPT: error: resource android:attr/lStar not found.
```

**Comment by gstory0404** [comment]
试试build.gradle改为一致
```
implementation "androidx.appcompat:appcompat:1.3.1"
```

**Comment by dalingng** [comment]
> implementation "androidx.appcompat:appcompat:1.3.1"

试过了不行

**Comment by gstory0404** [comment]
> > implementation "androidx.appcompat:appcompat:1.3.1"
> 
> 试过了不行

安卓编译版本升级34试试，可能官方sdk升级34了

**Comment by qingfeilin** [comment]
是的编译版本也改到34

**Comment by dalingng** [comment]
> > > implementation "androidx.appcompat:appcompat:1.3.1"
> > 
> > 
> > 试过了不行
> 
> 安卓编译版本升级34试试，可能官方sdk升级34了

换到问题了，把build.gradle里面的minSdkVersion改成21就可以了
