### ISSUE TITLE
FlutterUnionad.loadRewardVideoAd没有定义adLoadType

### ISSUE THREAD

**Issue by java8site** [gstory0404/flutter_unionad#119]
### 描述
> 异常/需求具体描述
激励视频，现在loadRewardVideoAd调用之后就直接播放了，没有预加载，我看adLoadType是用来配置是否预加载，但是这个方法里面没有定义这个参数
### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本
> 插件版本号
  flutter_unionad: ^2.0.8
### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
不调用show方法 不会播放



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月07日 18:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [gstory0404/flutter_unionad] FlutterUnionad.loadRewardVideoAd没有定义adLoadType (Issue #119) |

描述

异常/需求具体描述
激励视频，现在loadRewardVideoAd调用之后就直接播放了，没有预加载，我看adLoadType是用来配置是否预加载，但是这个方法里面没有定义这个参数

设备版本

本地flutter版本、设备型号版本

插件版本

插件版本号
flutter_unionad: ^2.0.8

日志

详细的log日志或者截图录屏

**Comment by java8site** [comment]
> 不调用show方法 不会播放
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年09月07日 18:10 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [gstory0404/flutter_unionad] FlutterUnionad.loadRewardVideoAd没有定义adLoadType (Issue #119) | 描述 异常/需求具体描述 激励视频，现在loadRewardVideoAd调用之后就直接播放了，没有预加载，我看adLoadType是用来配置是否预加载，但是这个方法里面没有定义这个参数 设备版本 本地flutter版本、设备型号版本 插件版本 插件版本号 flutter_unionad: ^2.0.8 日志 详细的log日志或者截图录屏 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

              FlutterUnionad.loadRewardVideoAd(
                //是否个性化 选填
                androidCodeId: "111",
                //Android 激励视频广告id  必填
                iosCodeId: "111",
                //ios 激励视频广告id  必填
                rewardName: "200金币",
                //奖励名称 选填
                rewardAmount: 200,
                //奖励数量 选填
                userID: "123",
                //  用户id 选填
                orientation: FlutterUnionadOrientation.VERTICAL,
                //视屏方向 选填
                mediaExtra: null,
                //扩展参数 选填

              );
              
              我真机器，ios和小米13，亲测，调完这个直接播放了。。。。。

**Comment by gstory0404** [comment]
回调监听怎么写的

**Comment by java8site** [comment]
> 回调监听怎么写的

    FlutterUnionadStream.initAdStream(
      //激励广告
      flutterUnionadRewardAdCallBack: FlutterUnionadRewardAdCallBack(
          onShow: (){
            print("激励广告显示");
          },
          onClick: (){
            print("激励广告点击");
          },
          onFail: (error){
            print("激励广告失败 $error");
          },
          onClose: (){
            print("激励广告关闭");
          },
          onSkip: (){
            print("激励广告跳过");
          },
          onVerify: (bool isVerify, int rewardAmount,
              String rewardName, int errorCode, String message){
            print("${DateTime.now()}激励广告奖励  $isVerify   $rewardAmount  $rewardName");
          },
          onReady: () async{
            print("激励广告预加载准备就绪");
          },
          onCache: () async {
            print("激励广告物料缓存成功。建议在这里进行广告展示，可保证播放流畅和展示流畅，用户体验更好。");
            await FlutterUnionad.showRewardVideoAd();
          },
          onUnReady: (){
            print("激励广告预加载未准备就绪");
          },
          onRewardArrived: (rewardVerify, rewardType, rewardAmount, rewardName,
              errorCode, error, propose) {
            print(
                "阶段激励广告奖励  验证结果=$rewardVerify 奖励类型<FlutterUnionadRewardType>=$rewardType 奖励=$rewardAmount"
                    "奖励名称$rewardName 错误码=$errorCode 错误$error 建议奖励$propose");
          }),
    );

我直接拉的demo的回调监听

**Comment by java8site** [comment]
> 回调监听怎么写的

FlutterUnionad.register也是demo的，只改了应用id

**Comment by gstory0404** [comment]
看看onReady回调

**Comment by java8site** [comment]
> showRewardVideoAd

看到了哈，多谢哈，打扰了。我关了

**Comment by java8site** [comment]
onReady里面，我写了调用播放，没发现，多谢大佬指点
