### ISSUE TITLE
运行一会儿闪退

### ISSUE THREAD

**Issue by 594904020** [gstory0404/flutter_unionad#12]
功能能正常使用，但是会闪退
Build fingerprint: 'samsung/dream2qltezh/dream2qltechn:7.1/N2G48H/G9550ZHU1AQEE:user/release-keys'
Revision: '12'
ABI: 'x86'
pid: 12382, tid: 12421, name: tt_pangle_threa  >>> com.example.flutterdemo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'stack corruption detected'
    eax 00000000  ebx 0000305e  ecx 00003085  edx 00000006
    esi 9c2ff978  edi 9c2ff920
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip c673dcc0  ebp 9c2fbb18  esp 9c2fbabc  flags 00200292
backtrace:
    #00 pc 00000cc0  [vdso:c673d000] (__kernel_vsyscall+16)
    #01 pc 0007bf2c  /system/lib/libc.so (tgkill+28)
    #02 pc 00077705  /system/lib/libc.so (pthread_kill+85)
    #03 pc 0002821a  /system/lib/libc.so (raise+42)
    #04 pc 0001eed6  /system/lib/libc.so (abort+86)
    #05 pc 00023de8  /system/lib/libc.so
    #06 pc 000793a3  /system/lib/libc.so (__stack_chk_fail+35)
    #07 pc 00001bb5  /data/app/com.example.flutterdemo-1/lib/x86/libnms.so
    #08 pc 016a7eac  /system/framework/x86/boot-framework.oat (offset 0x15b1000) (android.app.ContextImpl.getReceiverRestrictedContext+88)
    #09 pc 000fefc7  [stack:12421:9c1fd000]
Lost connection to device.

**Comment by gstory0404** [comment]
看下0.0.9版本还有这个问题吗

**Comment by maskletter** [comment]
我的0.09版本也是这样的情况欸
