### ISSUE TITLE
第一次运行报错

### ISSUE THREAD

**Issue by ch930410** [gstory0404/flutter_unionad#121]
直接拉取该git地址，在运行示例的报错如下：
当前环境为： 
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (4 months ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

 
 Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
E/FlutterLoader(12063): Flutter initialization failed.
E/FlutterLoader(12063): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/FlutterLoader(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/FlutterLoader(12063): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(12063): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:260)
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
E/FlutterLoader(12063): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setUpFlutterEngine(FlutterActivityAndFragmentDelegate.java:328)
E/FlutterLoader(12063): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:193)
E/FlutterLoader(12063): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638)
E/FlutterLoader(12063): 	at android.app.Activity.performCreate(Activity.java:7148)
E/FlutterLoader(12063): 	at android.app.Activity.performCreate(Activity.java:7139)
E/FlutterLoader(12063): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/FlutterLoader(12063): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
E/FlutterLoader(12063): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
E/FlutterLoader(12063): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/FlutterLoader(12063): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/FlutterLoader(12063): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/FlutterLoader(12063): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
E/FlutterLoader(12063): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader(12063): 	at android.os.Looper.loop(Looper.java:193)
E/FlutterLoader(12063): 	at android.app.ActivityThread.main(ActivityThread.java:6840)
E/FlutterLoader(12063): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(12063): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterLoader(12063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
E/FlutterLoader(12063): Caused by: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/FlutterLoader(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:209)
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:176)
E/FlutterLoader(12063): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(12063): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(12063): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(12063): 	at java.lang.Thread.run(Thread.java:764)
E/FlutterLoader(12063): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm, /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(12063): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1037)
E/FlutterLoader(12063): 	at java.lang.System.loadLibrary(System.java:1675)
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:147)
E/FlutterLoader(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:183)
E/FlutterLoader(12063): 	... 5 more
E/AndroidRuntime(12063): FATAL EXCEPTION: main
E/AndroidRuntime(12063): Process: com.gstory.flutter_unionad_example, PID: 12063
E/AndroidRuntime(12063): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gstory.flutter_unionad_example/com.gstory.flutter_unionad_example.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/AndroidRuntime(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/AndroidRuntime(12063): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
E/AndroidRuntime(12063): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
E/AndroidRuntime(12063): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(12063): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(12063): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(12063): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
E/AndroidRuntime(12063): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12063): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12063): 	at android.app.ActivityThread.main(ActivityThread.java:6840)
E/AndroidRuntime(12063): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12063): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
E/AndroidRuntime(12063): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/AndroidRuntime(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:377)
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
E/AndroidRuntime(12063): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setUpFlutterEngine(FlutterActivityAndFragmentDelegate.java:328)
E/AndroidRuntime(12063): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:193)
E/AndroidRuntime(12063): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638)
E/AndroidRuntime(12063): 	at android.app.Activity.performCreate(Activity.java:7148)
E/AndroidRuntime(12063): 	at android.app.Activity.performCreate(Activity.java:7139)
E/AndroidRuntime(12063): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(12063): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
E/AndroidRuntime(12063): 	... 11 more
E/AndroidRuntime(12063): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/AndroidRuntime(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/AndroidRuntime(12063): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(12063): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:260)
E/AndroidRuntime(12063): 	... 19 more
E/AndroidRuntime(12063): Caused by: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
E/AndroidRuntime(12063): App is using cpu architecture: armv7l, and the native libraries directory (with path /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm) contains the following files: [libpangleflipped.so, libzeus_direct_dex.so]
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:209)
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:176)
E/AndroidRuntime(12063): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(12063): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(12063): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(12063): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(12063): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/lib/arm, /data/app/com.gstory.flutter_unionad_example-iIogAG0hIO1sXH8cscIEUw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(12063): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1037)
E/AndroidRuntime(12063): 	at java.lang.System.loadLibrary(System.java:1675)
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:147)
E/AndroidRuntime(12063): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:183)
E/AndroidRuntime(12063): 	... 5 more

**Comment by ch930410** [comment]
java version "11.0.23" 2024-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.23+7-LTS-222)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.23+7-LTS-222, mixed mode)

**Comment by gstory0404** [comment]
用真机

**Comment by ch930410** [comment]
flutter emulators  
我用这个命令，他就初始化失败了

![image](https://github.com/user-attachments/assets/b648a12a-8d01-44e3-b78a-1e4b440a1af3)

**Comment by gstory0404** [comment]
穿山甲SDK不支持模拟机
