### ISSUE TITLE
example编译失败问题

### ISSUE THREAD

**Issue by FelixZ88** [gstory0404/flutter_unionad#132]
### 描述
> 异常/需求具体描述
FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'D:\Projects\flutter_unionad\example\android\settings.gradle' (C:\Users\xxx\.gradle\caches\7.6.3\scripts\6n6q3pxdm82y7574lqoruqqxo).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...                            3.4s

┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project's Gradle version is incompatible with the Java version that Flutter is using for Gradle.            │
│                                                                                                                      │
│ If you recently upgraded Android Studio, consult the migration guide at                                              │
│ https://flutter.dev/to/to/java-gradle-incompatibility.                                                               │
│                                                                                                                      │
│ Otherwise, to fix this issue, first, check the Java version used by Flutter by running `flutter doctor --verbose`.   │
│                                                                                                                      │
│ Then, update the Gradle version specified in                                                                         │
│ D:\Projects\flutter_unionad\example\android\gradle\wrapper\gradle-wrapper.properties to be compatible with that Java │
│ version. See the link below for more information on compatible Java/Gradle versions:                                 │
│ https://docs.gradle.org/current/userguide/compatibility.html#java                                                    │
│                                                                                                                      │
│                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
### 设备版本
> 本地flutter版本、设备型号版本

> Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    ! Warning: `flutter` on your path resolves to C:\Users\xxx\fvm\versions\3.24.3\bin\flutter, which is not inside
      your current Flutter SDK checkout at C:\Users\xxx\fvm\default. Consider adding C:\Users\xxx\fvm\default\bin to
      the front of your path.
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter
      SDK checkout at C:\Users\xxx\fvm\default. Consider adding C:\Users\mxxxngt\fvm\default\bin to the front of your
      path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.1)

### 插件版本
> 插件版本号

### 日志
> 详细的log日志或者截图录屏
```
![image](https://github.com/user-attachments/assets/626f1276-f135-4c79-8119-9dbe657cdf23)

```

Flutter版本号：3.24.2
Android Studio版本号：Android Studio Ladybug | 2024.2.1
Java版本号：java version "17.0.11" 2024-04-16 LTS

**Comment by gstory0404** [comment]
试试java11

**Comment by FelixZ88** [comment]
> 试试java11

降低到Java11后，又有了新的编译错误
![image](https://github.com/user-attachments/assets/47db1fee-39df-427e-b5ae-f28e6593f67b)
