### ISSUE TITLE
代码里给的例子崩溃了

### ISSUE THREAD

**Issue by maskletter** [gstory0404/flutter_unionad#16]
![image](https://user-images.githubusercontent.com/15777183/112162641-32461900-8c27-11eb-8f69-e596de7c6f47.png)
代码里给的例子崩溃了

**Comment by maskletter** [comment]
尝试过了，在手机上没事，在模拟器(我的是Genymotion)上面就会造成此问题

**Comment by maskletter** [comment]
我怀疑是open_ad_sdk.aar的问题，我用过另一个版本的穿山甲插件，那个的open_ad_sdk.aar大小3.6m具体版本不知，我在那个插件上用官网最新的aar运行在模拟上也会这样闪退，不懂原生开发，但是怀疑问题数出在此处

**Comment by maskletter** [comment]
@gstory0404

**Comment by gstory0404** [comment]
,0.1.0一更新最新的 可以测试一下 模拟器穿山甲无返回广告 最好以真机为准
