### ISSUE TITLE
为啥，我build老是报错

### ISSUE THREAD

**Issue by qyp19911009** [gstory0404/flutter_unionad#19]
Xcode's output:
↳
    warning: Stale file '/Users/flower/myFont/flutter-base/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework' is located outside of the allowed root paths.

    /Users/flower/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-0.1.0/ios/Classes/bannerad/BannerAdView.swift:48:54: warning: 'init(slotID:rootViewController:adSize:isSupportDeepLink:interval:)' is deprecated:
    Use initWithSlotID:rootViewController:adSize:interval: instead.
            let bannerAdView = BUNativeExpressBannerView.init(slotID: self.mCodeId!, rootViewController: MyUtils.getVC(), adSize: size, isSupportDeepLink: self.supportDeepLink!, interval: Int(self.expressTime!))
                                                         ^
    /Users/flower/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-0.1.0/ios/Classes/drawfeedad/DrawFeedAdView.swift:48:18: warning: 'isSupportDeepLink' is deprecated: This property is deprecated,Settings are no
    longer required after version 3300
            bUadSolt.isSupportDeepLink = self.supportDeepLink!
                     ^
    /Users/flower/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-0.1.0/ios/Classes/drawfeedad/DrawFeedAdView.swift:62:37: warning: 'loadAd' is deprecated: Use loadAdDataWithCount: instead.
            self.nativeExpressAdManager.loadAd(1)
                                        ^
    /Users/flower/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-0.1.0/ios/Classes/nativead/NativeAdView.swift:60:16: warning: 'isSupportDeepLink' is deprecated: This property is deprecated,Settings are no
    longer required after version 3300
            buSlot.isSupportDeepLink = self.supportDeepLink!
                   ^
    /Users/flower/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_unionad-0.1.0/ios/Classes/nativead/NativeAdView.swift:63:37: warning: 'loadAd' is deprecated: Use loadAdDataWithCount: instead.
            self.nativeExpressAdManager.loadAd(1)
                                        ^
    Undefined symbols for architecture arm64:
      "___cxa_current_primary_exception", referenced from:
          _hmdbu_current_cpp_exception in BUCNAuxiliary(hmdbu_cpp_exception.o)
    ld: symbol(s) not found for architecture arm64

**Comment by gstory0404** [comment]
穿山甲官方文档 里面xcode需要配置的东西 全部检查一下
