### ISSUE TITLE
集成安卓编译成功，但启动App时崩溃了

### ISSUE THREAD

**Issue by nasio-limbo** [gstory0404/flutter_unionad#27]
Flutter信息：
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)

步骤：
Built build/app/outputs/flutter-apk/app-debug.apk.
E/FlutterUnionadPlugin->(17839): onAttachedToEngine
E/FlutterUnionadPlugin->(17839): onAttachedToActivity

调用andridPrivacy时抛出异常：
_CastError (Null check operator used on a null value)

**Comment by gstory0404** [comment]
andridPrivacy flutter中的调用参数发一下

**Comment by nasio-limbo** [comment]
await Panglon.andridPrivacy(
    isCanUseLocation: false,
    isCanUsePhoneState: false,
    isCanUseWifiState: false,
    isCanUseWriteExternal: false,
  );

**Comment by gstory0404** [comment]
插件使用的那个版本？

**Comment by nasio-limbo** [comment]
找到问题了，调用插件前需要

    WidgetsFlutterBinding.ensureInitialized();
