### ISSUE TITLE
如何更新Android sdk与ios Sdk版本

### ISSUE THREAD

**Issue by jianjianXM** [gstory0404/flutter_unionad#28]

**Comment by gstory0404** [comment]
需要更新插件

**Comment by yy1300326388** [comment]
@jianjianXM @wenxiangjiang 
我使用这个插件[flutter_pangle_ads](https://github.com/FlutterAds/flutter_pangle_ads) 支持空安全，非常不错，有介绍如何升级插件 SDK 版本，无需等待插件更新
![image](https://user-images.githubusercontent.com/8764899/131304760-8e89628f-1e49-4496-a614-23d5bb5ff0e8.png)

**Comment by wenxiangjiang** [comment]
@yy1300326388 你好。
首先，并不赞同在这里提及同类插件，有广告嫌疑。
其次，我个人认为在插件不更新的情况下自己去更新原生 SDK 的意义不大。如果只是小版本更新，只是修改 bug 还好，如果有大更新插件的程序不修改也使用不到😄

**Comment by yy1300326388** [comment]
> @yy1300326388 你好。
> 
> 首先，并不赞同在这里提及同类插件，有广告嫌疑。
> 
> 其次，我个人认为在插件不更新的情况下自己去更新原生 SDK 的意义不大。如果只是小版本更新，只是修改 bug 还好，如果有大更新插件的程序不修改也使用不到😄

赞同，小更新可以的，大更新需要插件适配，目前来说广告SDK 都属于内部优化更新，所以还好的。

**Comment by wenxiangjiang** [comment]
@yy1300326388 嗯嗯，是的。
