### ISSUE TITLE
ios 开屏广告无法设置其大小

### ISSUE THREAD

**Issue by sparksworld** [gstory0404/flutter_unionad#3]
测试，Sizedbox，OverflowBox 仅对安卓生效，ios 无效

**Comment by gstory0404** [comment]
mac罢工拿去修了，等拿回来再修复

**Comment by sparksworld** [comment]
我只懂web端 ，看到客户端代码 实在乏力😄

**Comment by sparksworld** [comment]
> mac罢工拿去修了，等拿回来再修复

我只懂web端 ，看到客户端代码 实在乏力😄

**Comment by gstory0404** [comment]
平台创建开屏广告  只能选择未渲染模板  不能设置大小
