### ISSUE TITLE
信息流广告的触摸事件太流氓啦

### ISSUE THREAD

**Issue by ixugo** [gstory0404/flutter_unionad#35]
系统 : ios

请求帮助。

### 问题
被上层组件遮挡，碰一下上层组件，跳转广告了。距离说 底部的 BottomNavigationBar 遮挡了广告，点击按钮切换页面，却触发了被 BottomNavigationBar 遮住的广告。

信息流广告，滑动列表时误触，手指刚搭上去，就跳转广告了.... 

有点影响软件的使用了，请问有什么方法解决吗?

**Comment by gstory0404** [comment]
好像原生sdk中view拿取了焦点。暂时没有太好的解决方案

**Comment by ixugo** [comment]
哦哦😯
