### ISSUE TITLE
Oppo mobile phone prompts that there are ad plug-ins not recommended to install, how to solve this?

### ISSUE THREAD

**Issue by 2530442368** [gstory0404/flutter_unionad#38]
Oppo mobile phone prompts that there are ad plug-ins not recommended to install, how to solve this?
![image](https://user-images.githubusercontent.com/63909463/145701715-3de3669f-535c-423d-a7d0-1ee81b6c9a89.png)

**Comment by 2530442368** [comment]
flutter_unionad: ^1.1.9 用的是1.1.9版本

**Comment by gstory0404** [comment]
Using [brach_oppo](https://github.com/gstory0404/flutter_unionad/tree/brach_oppo) for oppe mobile phones，But the sdk version may not be the latest
