### ISSUE TITLE
ios广告存在点击穿透情况，android没有问题

### ISSUE THREAD

**Issue by sparksworld** [gstory0404/flutter_unionad#4]
### 问题描述
点击切换tab会穿透tab点击广告view

### 问题测试

1. 添加GestureDetector的`behavior: HitTestBehavior.opaque`验证无效
2. 使用AbsorbPointer 与 IgnorePointer 验证无效

[问题复现播放地址](https://grayscale-qktx.oss-cn-beijing.aliyuncs.com/h5cdn/Screen%20Recording%202020-10-23%20at%201.03.23%20PM_1603429719095320.mp4)

**Comment by gstory0404** [comment]
目前没找到 好用解决方案

**Comment by sparksworld** [comment]
最近浏览到一篇可能有用的文章,[地址点这里看一下](http://kmanong.top/kmn/qxw/form/article?id=14897&cate=119)

他截获touch事件防止冲突ios与flutter冲突

`- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    
    // 若为FlutterView（即点击了flutter），则不截获Touch事件
    if ([NSStringFromClass([touch.view class]) isEqualToString:@"FlutterView"]) {
        // 当手势在flutter上，由flutter处理
        NSLog(@"flutterView");
        return NO;
    }

    NSLog(@"native View");
    return  YES;
}`

**Comment by gstory0404** [comment]
好的 我这边有空研究一下

**Comment by xujinping** [comment]
@sparksworld 这么问题解决了吗？我也遇到同样的问题

**Comment by gstory0404** [comment]
暂时未解决

**Comment by BadReese** [comment]
> 暂时未解决

请问关闭issue是因为解决了?

**Comment by mmtou** [comment]
@gstory0404 大佬  现在有解决方案吗？

**Comment by gstory0404** [comment]
> gnizer:(UIGestur

//是否启用点击 仅ios生效 默认启用
    isUserInteractionEnabled: true,
    信息流现在对外提供控制是否可被点击参数，在广告被视图覆盖时修改参数

**Comment by mmtou** [comment]
我现在是插屏广告，点击关闭时会触发关闭按钮下方的其他按钮的点击事件，不知道能否设置呢？

**Comment by gstory0404** [comment]
> 我现在是插屏广告，点击关闭时会触发关闭按钮下方的其他按钮的点击事件，不知道能否设置呢？

我看下 暂时还没有遇到这个问题
