### ISSUE TITLE
iOS信息流广告，点击后无法跳转

### ISSUE THREAD

**Issue by BelindaShy** [gstory0404/flutter_unionad#40]
场景：显示信息流广告的VC如果是present出来的model视图，那么点击广告后无法跳转。

原因：定位是设置的rootViewController不对，作者可否修改下，直接返回当前最顶层控制器？

个人实验代码，返回当前最顶层控制器，那么present出来的广告可以正常点击跳转。
修改代码如下：

class MyUtils{
    static func getVC() -> UIViewController {
        let vc = UIApplication.shared.delegate?.window??.rootViewController
        if let vc = vc  {
            return findBestViewController(vc: vc)
        }
        return UIViewController.init()
        }

    class func findBestViewController(vc : UIViewController) -> UIViewController {

        if vc.presentedViewController != nil {
            return findBestViewController(vc: vc.presentedViewController!)
        } else if vc.isKind(of:UISplitViewController.self) {
            let svc = vc as! UISplitViewController
            if svc.viewControllers.count > 0 {
                return findBestViewController(vc: svc.viewControllers.last!)
            } else {
                return vc
            }
        } else if vc.isKind(of: UINavigationController.self) {
            let nvc = vc as! UINavigationController
            if nvc.viewControllers.count > 0 {
                return findBestViewController(vc: nvc.topViewController!)
            } else {
                return vc
            }
        } else if vc.isKind(of: UITabBarController.self) {
            let tvc = vc as! UITabBarController
            if (tvc.viewControllers?.count)! > 0 {
                return findBestViewController(vc: tvc.selectedViewController!)
            } else {
                return vc
            }
        } else {
            return vc
        }
    }
    
    //获取屏幕尺寸
    static func getScreenSize() -> CGRect {
        let screenBounds:CGRect = UIScreen.main.bounds
        return screenBounds
    }
}

**Comment by gstory0404** [comment]
好的👌🏻 感谢
