### ISSUE TITLE
iOS在广告页上显示弹窗，点击弹窗，底层的广告会响应点击事件。

### ISSUE THREAD

**Issue by BelindaShy** [gstory0404/flutter_unionad#42]
如题，以showModalBottomSheet方式或PageRouteBuilder方式显示弹窗，点击弹窗之后底部的广告都会响应点击事件。
请问有什么办法解决啊？

**Comment by gstory0404** [comment]
sdk原生点击事件与flutter点击事件冲突导致，暂时没有太好的解决方案

**Comment by BelindaShy** [comment]
> sdk原生点击事件与flutter点击事件冲突导致，暂时没有太好的解决方案

是指穿山甲sdk与flutter点击事件冲突吗？广告sdk内部可以修改吗，如果可以的话我们这边可以联系他们提问题。

**Comment by gstory0404** [comment]
点击事件是sdk内部触发的  无法修改触发方法

**Comment by BelindaShy** [comment]
> 点击事件是sdk内部触发的 无法修改触发方法

没太明白😅

**Comment by BelindaShy** [comment]
![image](https://user-images.githubusercontent.com/77422980/152914917-896c6c05-079f-4849-b8f6-acce078c9a8c.png)
如果广告sdk这么修改下，是否可以？

**Comment by gstory0404** [comment]
> > 点击事件是 sk 内部触发的无法修改触发方法
> 
> 没太明白😅

SDK获取触点 触发点击，与flutter的点击冲突。flutter触发了点击事件，响应的IOS也触发了点击。暂时没有找到触发flutter点击拦截原生获取触发的方案。

**Comment by BelindaShy** [comment]
> > > 点击事件是 sk 内部触发的无法修改触发方法
> > 
> > 
> > 没太明白😅
> 
> SDK获取触点 触发点击，与flutter的点击冲突。flutter触发了点击事件，响应的IOS也触发了点击。暂时没有找到触发flutter点击拦截原生获取触发的方案。

![image](https://user-images.githubusercontent.com/77422980/152915621-d4cca379-86b1-4bda-836d-cf53cbfaaf06.png)

广告view这么修改可以解决吗？

**Comment by gstory0404** [comment]
> > > > 点击事件是 sk 内部触发的无法修改触发方法
> > > 
> > > 
> > > 没太明白😅
> > 
> > 
> > SDK获取触点 触发点击，与flutter的点击冲突。flutter触发了点击事件，响应的IOS也触发了点击。暂时没有找到触发flutter点击拦截原生获取触发的方案。
> 
> ![image](https://user-images.githubusercontent.com/77422980/152915621-d4cca379-86b1-4bda-836d-cf53cbfaaf06.png)
> 
> 广告view这么修改可以解决吗？

尝试过 不起作用

**Comment by rockingdice** [comment]
我也遇到类似的问题了，不少iOS的用户广告一直疯狂弹出。请问有没有办法临时处理让广告不影响flutter的页面？目前这样子实在是很影响app的评分…比如加一个flutter的设置参数，设置为false时就隐藏掉广告。
我目前就是这么处理的，但是还是没办法解决，不清楚为什么。我的做法是当用户弹窗后，我让flutter的界面刷新（setState），把后面的广告widget去掉（不执行FlutterUnionad.nativeAdView方法），按理说广告已经都不显示出来了，也没有加到widgetTree里，但是用户仍然反馈频繁弹广告。我想应该和原生view有一些关系？

**Comment by gstory0404** [comment]
> 我也遇到类似的问题了，不少iOS的用户广告一直疯狂弹出。请问有没有办法临时处理让广告不影响flutter的页面？目前这样子实在是很影响app的评分…比如加一个flutter的设置参数，设置为false时就隐藏掉广告。 我目前就是这么处理的，但是还是没办法解决，不清楚为什么。我的做法是当用户弹窗后，我让flutter的界面刷新（setState），把后面的广告widget去掉（不执行FlutterUnionad.nativeAdView方法），按理说广告已经都不显示出来了，也没有加到widgetTree里，但是用户仍然反馈频繁弹广告。我想应该和原生view有一些关系？

flutter widget在原生view上层，虽然页面上被遮盖 但是实际点击事件还是传递到原生view了 所以导致广告被触发

**Comment by rockingdice** [comment]
@gstory0404 谢谢解答，那么请问原生view是否会跟随widget移动呢?因为信息流是会滚动的，有时会跑出屏幕范围外部，此时原生view是否会跟随移动到屏幕外呢? 因为从现在测试的情况来看，好像并没有用。

另外还有一个问题，如果我在setState时重建了flutter的widget，但是重新设定了ads的尺寸，比如原来设置300x200的广告，
后面如果刷新时改为1x1，原生view是否也会随之改变呢？如果点击区域也可以缩小到1x1，也可以临时解决目前的问题了（0x0好像不行因为会用默认尺寸?）

**Comment by gstory0404** [comment]
> @gstory0404 谢谢解答，那么请问原生view是否会跟随widget移动呢?因为信息流是会滚动的，有时会跑出屏幕范围外部，此时原生view是否会跟随移动到屏幕外呢? 因为从现在测试的情况来看，好像并没有用。
> 
> 另外还有一个问题，如果我在setState时重建了flutter的widget，但是重新设定了ads的尺寸，比如原来设置300x200的广告， 后面如果刷新时改为1x1，原生view是否也会随之改变呢？如果点击区域也可以缩小到1x1，也可以临时解决目前的问题了（0x0好像不行因为会用默认尺寸?）

原生view不会改变，大小只有在创建时传入有效。因为UiKitView、AndroidView需要一个有宽高的容器，所以必须大于1x1

**Comment by gstory0404** [comment]
v1.3.5 开始banner、信息流广告 新增isUserInteractionEnabled 以控制广告是否可被点击。在被遮罩后 手动设置false来使其不可点击
