### ISSUE TITLE
ios激励视频onVerify 因errorCode和error类型错误导致回调失败

### ISSUE THREAD

**Issue by JulyEve** [gstory0404/flutter_unionad#44]
![fOXqGbcWzE](https://user-images.githubusercontent.com/18692248/156119638-f6d6e22f-5531-446b-9bb8-d5c9f6b498b4.png)
![nmij3Gd4wJ](https://user-images.githubusercontent.com/18692248/156119643-83a00db5-fd48-44a5-98d9-e299347a88e4.png)

**Comment by gstory0404** [comment]
@JulyEve 查看一下后台日志 有个RewardVideoAd的log  看下激励广告观看完成的回调参数

**Comment by gstory0404** [comment]
> ![fOXqGbcWzE](https://user-images.githubusercontent.com/18692248/156119638-f6d6e22f-5531-446b-9bb8-d5c9f6b498b4.png) ![nmij3Gd4wJ](https://user-images.githubusercontent.com/18692248/156119643-83a00db5-fd48-44a5-98d9-e299347a88e4.png)

插件版本号 多少

**Comment by JulyEve** [comment]
> 

1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的

**Comment by gstory0404** [comment]
> > 
> 
> 1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的

穿山甲后台 是否设置了激励广告服务器验证？

**Comment by JulyEve** [comment]
> > > 
> > 
> > 
> > 1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的
> 
> 穿山甲后台 是否设置了激励广告服务器验证？

没有开启服务器验证

**Comment by JulyEve** [comment]
> > > > 
> > > 
> > > 
> > > 1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的
> > 
> > 
> > 穿山甲后台 是否设置了激励广告服务器验证？
> 
> 没有开启服务器验证

返回的data数据有断点，确实没看到errorcode的数据

**Comment by gstory0404** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的
> > > 
> > > 
> > > 穿山甲后台 是否设置了激励广告服务器验证？
> > 
> > 
> > 没有开启服务器验证
> 
> 返回的data数据有断点，确实没看到errorcode的数据

```
flutter_unionad:
    git:
      url: https://github.com/gstory0404/flutter_unionad.git
      ref: dev
```
引用dev分支的插件 试一下

**Comment by gstory0404** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 1.1.5跟1.2.4都试过了，都不行，源代码看也是一样的
> > > > > 
> > > > > 
> > > > > 穿山甲后台 是否设置了激励广告服务器验证？
> > > > 
> > > > 
> > > > 没有开启服务器验证
> > > 
> > > 
> > > 返回的data数据有断点，确实没看到errorcode的数据
> > 
> > 
> > ```
> > flutter_unionad:
> >     git:
> >       url: https://github.com/gstory0404/flutter_unionad.git
> >       ref: dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 引用dev分支的插件 试一下
> 
> 这个是可以解决data数据问题，但是可能引起了另一个ios卡屏的问题。能不能问下dev改动了哪里修复了这个问题，我是否可以自己先修复下。

你那边应该走到服务器验证失败的方法，目测后台开启了激励广告验证，修改了验证失败后sdk返回error空判断
卡屏是什么样的？

**Comment by gstory0404** [comment]
@JulyEve 是重启后激励广告无法点击吗

**Comment by JulyEve** [comment]
> @JulyEve 是重启后激励广告无法点击吗

不是的，是app会卡主不动。反复测试了好几次，1.1.5正常。1.2.4就会出现。release版本尤其明显。必现流程：打包release，启动，然后完全退出app再进入就会。

**Comment by gstory0404** [comment]
> > @JulyEve 是重启后激励广告无法点击吗
> 
> 不是的，是app会卡主不动。反复测试了好几次，1.1.5正常。1.2.4就会出现。release版本尤其明显。必现流程：打包release，启动，然后完全退出app再进入就会。

https://www.pgyer.com/09cI 下载这个demo试一下

**Comment by JulyEve** [comment]
> 

安卓没问题的，ios才会出现。

**Comment by JulyEve** [comment]
@gstory0404 卡的问题换个方式先解决了。这个回调问题什么时候会合并到正式分支发布呀

**Comment by gstory0404** [comment]
@JulyEve 明天吧  还有点问题在优化

**Comment by JulyEve** [comment]
好的，非常感谢回复

**Comment by gstory0404** [comment]
> 好的，非常感谢回复

已发布了v1.2.5
