### ISSUE TITLE
合规问题

### ISSUE THREAD

**Issue by LuodiJackShen** [gstory0404/flutter_unionad#46]
上传华为应用市场时被驳回了，提了下面两个问题：

> 尊敬的开发者，您好，
1，当用户点击暂停广告，再次回到应用内广告页面，并再次点击广告后也需要弹窗提示用户确认是否下载；
> 2，根据审核规则，需要确保通知栏的消息都可以正常关闭，请优化修改。谢谢。

第一个问题，当用户第一次点击app下载类的广告时会有确认弹窗，并且能弹出下载进度的通知栏，此时这个通知栏是无法关闭的。
第二个问题，当用户在下载通知栏中点击暂停下载后，再回到应用内点击广告，此时会直接继续下载，并不会有确认下载框了。
请问这两个问题该怎么解决呢？是否有对应的api？谢谢！

**Comment by gstory0404** [comment]
第一个官方sdk没有处理
第二个点击会有删除任务弹窗

**Comment by gstory0404** [comment]
> 第一个官方sdk没有处理 第二个点击会有删除任务弹窗

使用最新版本插件，官方最新sdk会尽量同步更新

**Comment by LuodiJackShen** [comment]
请问下其他开发者是怎么处理的第一种情况，是怎么过审的

**Comment by gstory0404** [comment]
> 请问下其他开发者是怎么处理的第一种情况，是怎么过审的

我没有上架华为的 其他的暂时没有反馈。有安装应用商城的情况下 推送的广告大多都是打开商城

**Comment by LuodiJackShen** [comment]
好的，谢谢，我去问问穿山甲客服。
