### ISSUE TITLE
有些应用商店要求app能够关闭个性化推荐广告，能否把sdk的相应配置在flutter中暴露出来

### ISSUE THREAD

**Issue by danieldai** [gstory0404/flutter_unionad#48]
现在个人信息保护法和有些应用商店都要求能够关闭个性化推荐广告，穿山甲的SDK也已经提供了相应的支持，能否把sdk的相应配置在flutter中暴露出来？

穿山甲文档链接：https://www.csjplatform.com/supportcenter/26234

感谢大佬！

**Comment by gstory0404** [comment]
v1.2.8 看一下
