### ISSUE TITLE
android 下 激励视频有bug?

### ISSUE THREAD

**Issue by ArthurKnight** [gstory0404/flutter_unionad#5]
android下激励视频播放完后，显示的rewardName 永远是第一次加载的那个名字? 卸载了app重装还是一样。 ios没有此问题

**Comment by ArthurKnight** [comment]
请问信息流的高度必须要设置吗，无法自适应么？

**Comment by gstory0404** [comment]
如果本地存在同一个广告id拉去的广告会读取上次广告的数据。高度必须设置，flutter调用原生view，Androidview uikitview宽高无限大，需要container等widget等设置宽高限定
