### ISSUE TITLE
release编译后FlutterUnionad.splashAdView报错flutter_unionad is not init, please check

### ISSUE THREAD

**Issue by nodelinker** [gstory0404/flutter_unionad#51]
Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.19043.1706], locale zh-CN)

`
PlatformException(error, flutter_unionad is not init, please check., null, java.lang.RuntimeException: flutter_unionad is not init, please check. at f.c.a.f.c(Unknown Source:18) at f.c.a.n.a.<init>(Unknown Source:188) at f.c.a.n.b.create(Unknown Source:14) at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(Unknown Source:73) at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(Unknown Source:232) at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(Unknown Source:175) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17) at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18) at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:20) at io.flutter.embedding.engine.dart.DartMessenger.b(Unknown Source:0) at io.flutter.embedding.engine.dart.c.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler....too long be cutted!
`

>出错堆栈

1	#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
2	#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
3	<asynchronous suspension>
4	#2 TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1134)
5	<asynchronous suspension>
6	#3 AndroidViewController.create (package:flutter/src/services/platform_views.dart:762)
7	<asynchronous suspension>
8	#4 TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1062)
9	<asynchronous suspension>
10	#5 RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179)
11	<asynchronous suspension>

**Comment by gstory0404** [comment]
调用任何广告前必须初始化 ​FlutterUnionad​.​register

**Comment by nodelinker** [comment]
我是在main函数里调用了register，在debug测试没有任何问题。只是编译release版以后，出现白屏。

错误是bugly捕获的信息。

**Comment by nodelinker** [comment]
我编译了example做对比，没有出错。难道是需要设置什么选项？

**Comment by nodelinker** [comment]
确认了一下, 如果设置initialRoute: '/splash_page'，并且在splash_page里调用FlutterUnionad.splashAdView一定会报错。

如果在home_page里面随便button触发'/splash_page'就没有问题了，这是在release编译后真机运行的情况。

所以猜测应该是启动的时机的问题。

**Comment by gstory0404** [comment]
> 确认了一下, 如果设置initialRoute: '/splash_page'，并且在splash_page里调用FlutterUnionad.splashAdView一定会报错。
> 
> 如果在home_page里面随便button触发'/splash_page'就没有问题了，这是在release编译后真机运行的情况。
> 
> 所以猜测应该是启动的时机的问题。

FlutterUnionad​.​register 返回值一定是true时 才能调用广告

**Comment by TestSmirk** [comment]
混淆了

**Comment by zanpen2000** [comment]
遇到了同样的问题，请问问题解决了吗？如何解决的？

**Comment by gstory0404** [comment]
在splashpage中定一个一个是否初始化的变量 当为true的时候 开始加载开屏广告，否则不加载

**Comment by gstory0404** [comment]
> 遇到了同样的问题，请问问题解决了吗？如何解决的？
> 
> 我确定初始化的时候是FlutterUnionad​.​register=true的， 然后也避免了混淆

在splashpage中定一个一个是否初始化的变量 当为true的时候 开始加载开屏广告，否则不加载
