### ISSUE TITLE
requires that an explicit value

### ISSUE THREAD

**Issue by bingoming** [gstory0404/flutter_unionad#52]
![image](https://user-images.githubusercontent.com/30516379/170451635-5dfd52aa-6d31-4ab9-8919-a41fbeef7d47.png)
安卓12
TTnetDebugActivity这个在哪配置?

**Comment by gstory0404** [comment]
建议向官方提交工单资讯

**Comment by bingoming** [comment]
![image](https://user-images.githubusercontent.com/30516379/170459615-81d109ee-975d-46f1-84b6-f1e887ac1c6c.png)
也不知道这个类哪来的

**Comment by gstory0404** [comment]
没有这个类

**Comment by bingoming** [comment]
![1653558313(1)](https://user-images.githubusercontent.com/30516379/170463523-6568485d-21a6-486b-965a-fec7e87ff5e2.jpg)

**Comment by gstory0404** [comment]
你发错地方了这个内容合作sdk中的东西
com.bytedance.frameworks.baselib:ttnet:4.0.27.1-rc.4-tob@aar这个包中的文件
```
 <application android:label="@string/app_name" >
        <activity
            android:name="com.bytedance.ttnet.debug.TTnetDebugActivity"
            android:configChanges="keyboardHidden|orientation" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="page"
                    android:scheme="ttnet_debug" />
            </intent-filter>
        </activity>
    </application>
```
向官方资讯一下

**Comment by bingoming** [comment]
![image](https://user-images.githubusercontent.com/30516379/170465474-8b66ef9f-819e-4847-b155-2fb6f267db7e.png)
工单还没回,自行找到一个解决方式
在AndroidManifest.xml-application中加入一个activity覆盖掉依赖包中定义了
<activity
           android:name="com.bytedance.ttnet.debug.TTnetDebugActivity"
           android:configChanges="keyboard|orientation|screenSize"
           android:launchMode="singleTop"
           android:screenOrientation="portrait"
           android:exported="true"
           tools:replace="android:configChanges"
           android:theme="@style/AppFull" />

**Comment by bingoming** [comment]
![image](https://user-images.githubusercontent.com/30516379/170466066-b11d487b-cf27-4eb3-8944-6f31e6379aea.png)

**Comment by gstory0404** [comment]
资讯官方处理吧 自己覆盖 可能会出现 不可知问题

**Comment by bingoming** [comment]
官方给解决自然更好

**Comment by gstory0404** [comment]
> 你发错地方了这个内容合作sdk中的东西 com.bytedance.frameworks.baselib:ttnet:4.0.27.1-rc.4-tob@aar这个包中的文件
> 
> ```
>  <application android:label="@string/app_name" >
>         <activity
>             android:name="com.bytedance.ttnet.debug.TTnetDebugActivity"
>             android:configChanges="keyboardHidden|orientation" >
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
> 
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
> 
>                 <data
>                     android:host="page"
>                     android:scheme="ttnet_debug" />
>             </intent-filter>
>         </activity>
>     </application>
> ```
> 
> 向官方资讯一下

@bingoming bin 这个发给官方 他应该就知道了

**Comment by bingoming** [comment]
![image](https://user-images.githubusercontent.com/30516379/170643438-f177ef95-44e5-468b-81e0-271e3e420007.png)

**Comment by gstory0404** [comment]
等他做了兼容 我再同步更新一下
