### ISSUE TITLE
开屏广告没有显示

### ISSUE THREAD

**Issue by 76765357** [gstory0404/flutter_unionad#53]
其他激励、插屏正常

**Comment by wangpeishihang** [comment]
请问你解决了么？什么问题啊，我也显示不了开屏广告

**Comment by gstory0404** [comment]
后台有什么错误日志吗 

> 请问你解决了么？什么问题啊，我也显示不了开屏广告

**Comment by wangpeishihang** [comment]
没有任何错误，我解决了，只能作为widget调用，我还以为能像激励广告一样调用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月31日(周二) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gstory0404/flutter_unionad] 开屏广告没有显示 (Issue #53)




 
后台有什么错误日志吗
  
请问你解决了么？什么问题啊，我也显示不了开屏广告
