### ISSUE TITLE
开屏广告的加载类型默认为UNKNOWN，官方文档中提到为了收益最大化应该设置为实时

### ISSUE THREAD

**Issue by MEIIT** [gstory0404/flutter_unionad#54]
android官方文档开屏广告注意点的第3点，“3、为了收益最大化所有开屏广告均要实时请求，不可缓存。”，那么setAdLoadType()应该设置为LOAD实时

**Comment by gstory0404** [comment]
下个版本 开放相关参数出来@MEIIT

**Comment by gstory0404** [comment]
下个版本 开放相关参数出来@MEIIT

**Comment by gstory0404** [comment]
v1.3.4已新增
