### ISSUE TITLE
聚合sdk的支持

### ISSUE THREAD

**Issue by LuodiJackShen** [gstory0404/flutter_unionad#57]
请问是否有开发穿山甲 GroMore sdk flutter版本的计划？

**Comment by gstory0404** [comment]
[flutter_universalad](https://github.com/gstory0404/flutter_universalad) 目前已提供穿山甲、优量汇聚合。GroMore大部分人用不到那么多广告平台导致包太大，暂时没有开发计划

**Comment by LuodiJackShen** [comment]
1、[flutter_universalad](https://github.com/gstory0404/flutter_universalad) 这个支持两者的竞价吗？还是仅仅是接入了两个平台？
2、GroMore我测试了下，如果只接入穿山甲和百度的话，安装包大概增加5M左右，对我们的产品来讲还能接受，主要是收益高，看别人的测评，收益大概提高40%左右

**Comment by gstory0404** [comment]
> 1、[flutter_universalad](https://github.com/gstory0404/flutter_universalad) 这个支持两者的竞价吗？还是仅仅是接入了两个平台？ 2、GroMore我测试了下，如果只接入穿山甲和百度的话，安装包大概增加5M左右，对我们的产品来讲还能接受，主要是收益高，看别人的测评，收益大概提高40%左右

目前是不支持竞价，只能动态配置 两家平台广告的展示频率来达到最优收益。GroMore在单一原生平台接入好处理，flutter多端来做需要同时接入多家sdk来处理，可能导致引入不需要的sdk导致包过大，因为每个人的需求都不一致。后续看能不能原生部分封装一下动态插入，flutter来统一调用，如果能实现可以接入。

**Comment by LuodiJackShen** [comment]
可以让我们自己在业务工程里接入想要接入的广告sdk以及对应的adapter包，plugin里只接入最基础的gromore sdk以及必须的其他依赖。如果可以的话，可以一块开发，能省点时间。

**Comment by gstory0404** [comment]
> 可以让我们自己在业务工程里接入想要接入的广告sdk以及对应的adapter包，plugin里只接入最基础的gromore sdk以及必须的其他依赖。如果可以的话，可以一块开发，能省点时间。

可以尝试

**Comment by LuodiJackShen** [comment]
期待大佬早日开发出来

**Comment by gstory0404** [comment]
> 期待大佬早日开发出来

隔壁好像有人已经开发了 可以直接用他的

**Comment by gstory0404** [comment]
> 你说的是哪个？我找到一个，但是不支持banner类型的广告 https://github.com/FlutterAds/flutter_gromore_ads

嗯 是这个

**Comment by LuodiJackShen** [comment]
哈哈，他目前不支持banner，而且也没有计划支持banner:joy: 您这边是否有计划支持gromore的所有类型:smile:

**Comment by gstory0404** [comment]
> 哈哈，他目前不支持banner，而且也没有计划支持banner😂 您这边是否有计划支持gromore的所有类型😄

因为弹窗 激励等广告 好处理  调用api就行，原生view广告处理的东西很多，后续有空可以看看，毕竟写的插件有点多 维护也费时间，空闲世间没那么多

**Comment by LuodiJackShen** [comment]
好的，如果有需要我也可以一块写

**Comment by gstory0404** [comment]
@LuodiJackShen 可以关注聚合广告[gromore](https://github.com/gstory0404/gromore )仓库

**Comment by gstory0404** [comment]
@LuodiJackShen 加下好友

**Comment by LuodiJackShen** [comment]
> @LuodiJackShen 加下好友

邮件发你了
