### ISSUE TITLE
视频类型的banner广告

### ISSUE THREAD

**Issue by LuodiJackShen** [gstory0404/flutter_unionad#58]
在首页的顶部有一个banner类型的广告，当此广告是视频类型的时候会自动播放，用户点击按钮进入第二个页面时，视频仍然会播放，并且会展示在前台，请问这种情况怎么解决？
![WechatIMG218](https://user-images.githubusercontent.com/25525335/179132771-df58637f-ee48-4a7c-9f83-57803f22b686.jpeg)

**Comment by gstory0404** [comment]
andorid、ios都会出现吗

**Comment by LuodiJackShen** [comment]
手头还没有iOS手机，没法看，Android是必现

**Comment by gstory0404** [comment]
无法复现

**Comment by LuodiJackShen** [comment]
你那看视频类型的banner没法复现吗？能贴下代码不，我对比下

**Comment by gstory0404** [comment]
提供的测试demo

> 你那看视频类型的banner没法复现吗？能贴下代码不，我对比下

**Comment by LuodiJackShen** [comment]
你能加载出视频类型的banner吗？我用你的demo试了半天了，一直没有视频类型的banner呢

**Comment by gstory0404** [comment]
刷不出来

**Comment by LuodiJackShen** [comment]
行吧，我再排查排查吧

**Comment by LuodiJackShen** [comment]
破案了。初始化的时候，无比将useTextureView设置为true，否则就会出现我截图的那个问题。
