### ISSUE TITLE
目前回调是不是无法知道是来自哪个广告ID？

### ISSUE THREAD

**Issue by zeewell** [gstory0404/flutter_unionad#59]
如题：目前的广告回调是不是无法知道是来自哪个广告ID？

我好像没有找到相关的使用方法。

**Comment by zeewell** [comment]
比如 FlutterUnionad.loadRewardVideoAd 没有callback方法；
FlutterUnionadStream.initAdStream 的 flutterUnionadRewardAdCallBack 也没有回传广告的ID

不知道是不是我理解错了？

**Comment by zeewell** [comment]
> 先传入一个广告预加载，同时只存在一个预加载的缓存 怎么会不知道是哪个adid

那可能是我哪里理解的不对？

比如，我调用了FlutterUnionad.loadRewardVideoAd，再调用 FlutterUnionad.showRewardVideoAd，此时如何获取激励视频的验证结果？我这里有几个不同广告ID的激励视频都需要调用。

怎么使用才是正确的呢？求助！

**Comment by gstory0404** [comment]
预加载的激励广告 永远只会存在一条。调用show会播放当前加载的广告，如果不存在的话会返回onUnReady，重新调用加载方法。

**Comment by gstory0404** [comment]
```
onVerify: (rewardVerify,rewardAmount,rewardName){
          print("激励广告奖励  $rewardVerify   $rewardAmount  $rewardName");
        },
onRewardArrived: (rewardVerify, rewardType, rewardAmount, rewardName,
          errorCode, error, propose) {
            print(
            "阶段激励广告奖励  验证结果=$rewardVerify 奖励类型<FlutterUnionadRewardType>=$rewardType 奖励=$rewardAmount"
            "奖励名称$rewardName 错误码=$errorCode 错误$error 建议奖励$propose");
            }),
```
前端验证的话 加载广告时传入的奖励会回调回来，后端验证的话，看你们后端的逻辑，如果非要找当前广告的话，onReady做本地缓存吧，广告时单例处理的有且只会存在一条

**Comment by zeewell** [comment]
不知道有没有计划在调用 `FlutterUnionad.loadRewardVideoAd` 或 `FlutterUnionad.showRewardVideoAd` 时传入回调？就像 `FlutterUnionad.splashAdView` 这样处理感觉还是舒服些。集中式处理有时感觉不太方便。

**Comment by gstory0404** [comment]
因为预加载一般需要在在任何页面播放，可以在flutter中建立一个单例来控制。如果需要记录id的话，load时记录当前使用的广告id来处理

**Comment by gstory0404** [comment]
> 因为预加载一般需要在在任何页面播放，可以在flutter中建立一个单例来控制。如果需要记录id的话，load时记录当前使用的广告id来处理

单纯的及时加载播放就失去了预加载的意义
