### ISSUE TITLE
打包后体积增大很多

### ISSUE THREAD

**Issue by zanpen2000** [gstory0404/flutter_unionad#65]
直接贴个图吧

![image](https://user-images.githubusercontent.com/3360804/189791491-d36336c7-a425-4c29-a042-1bc4f4f092b0.png)

解压出来看了下，应该是插件sdk的？

请问有没有办法减小打包体积？

**Comment by gstory0404** [comment]
原始sdk aar文件就6.7M

**Comment by zanpen2000** [comment]
看来是没有办法了， 我看他是打了一个zip包整整5M， 真是要了亲命了
