### ISSUE TITLE
编译时一直报jks错误，请问应该怎么办？

### ISSUE THREAD

**Issue by WEHOOK** [gstory0404/flutter_unionad#66]
![image](https://user-images.githubusercontent.com/24522145/191133691-0133f7cd-df3f-47fe-9e7c-18a05a978aaa.png)

![image](https://user-images.githubusercontent.com/24522145/191133892-c3a0511e-fbb5-4070-bcc1-21a100305290.png)

**Comment by gstory0404** [comment]
@WEHOOK 重新pull一下
