### ISSUE TITLE
iOS端卡屏SplashAd调起AppStore安装页卡死

### ISSUE THREAD

**Issue by huntrist** [gstory0404/flutter_unionad#68]
倒计时停止，无法跳过，但是可以再次调起AppStore
可能增加splashAdDidCloseOtherController回调可以解决问题？

**Comment by gstory0404** [comment]
https://www.github.com/gstory0404/flutter_unionad/tree/master/notice.md
配置了吗

**Comment by huntrist** [comment]
配置了。
我碰到的问题不是不能点击。
如果是点击跳转其他APP或者跳转网页的广告是没问题的。
只有点击调起AppStore安装的才有卡死的问题。
尝试了增加splashAdDidCloseOtherController，貌似没有解决问题。

**Comment by gstory0404** [comment]
插件版本多少

> 配置了。 我碰到的问题不是不能点击。 如果是点击跳转其他APP或者跳转网页的广告是没问题的。 只有点击调起AppStore安装的才有卡死的问题。

**Comment by huntrist** [comment]
> 插件版本多少
> 
> > 配置了。 我碰到的问题不是不能点击。 如果是点击跳转其他APP或者跳转网页的广告是没问题的。 只有点击调起AppStore安装的才有卡死的问题。

插件和flutter都是最新版本：
flutter_unionad 1.3.14
flutter 3.3.2

**Comment by huntrist** [comment]
疑似问题是因为在onClick事件中使用setState触发了Navigator.push。
所以使用插件的时候，在onClick事件中慎用setState及跳转逻辑。

**Comment by gstory0404** [comment]
onClick事件 尽量不要做任何处理，原生广告会做计时暂停、跳转逻辑，回来计时计数会触发onFinish再做Navigator.push，onClick回调一般都是用来做埋点统计

> 疑似问题是因为在onClick事件中使用setState触发了Navigator.push。 所以使用插件的时候，在onClick事件中慎用setState及跳转逻辑。
