### ISSUE TITLE
激励视频广告能否过程中关闭

### ISSUE THREAD

**Issue by zanpen2000** [gstory0404/flutter_unionad#72]
## 感谢开发者提供这么好的插件

**有个上架华为的问题.**

"您的应用内广告存在弹出后无法立即关闭，不符合华为应用市场审核标准".

视频太大没办法传上来, 

总之就是激励视频右上角只有倒数读秒,没有关闭或跳过按钮, 不知道这个问题应该怎么处理?

**Comment by gstory0404** [comment]
sdk默认无法提前关闭，官方提交工单联系技术定制 @zanpen2000

**Comment by zanpen2000** [comment]
好的, 谢谢回复 @gstory0404
