### ISSUE TITLE
请问该插件支持海外版(pangleglobal.com)吗?

### ISSUE THREAD

**Issue by zanpen2000** [gstory0404/flutter_unionad#73]
作者你好,  请问该插件支持海外版(pangleglobal.com)吗?

![image](https://user-images.githubusercontent.com/3360804/196877212-66c7c80a-7d0d-443a-89f1-25cce17bf118.png)

不知道各位是如何处理海外用户的访问的? 可以提供一下思路吗?

**Comment by gstory0404** [comment]
暂时不支持海外，海外需要联系穿山甲商务开通
