### ISSUE TITLE
ios信息流会穿透弹窗触发

### ISSUE THREAD

**Issue by yingmiaohuangg** [gstory0404/flutter_unionad#75]
我使用modal_bottom_sheet弹窗，操作弹窗内容会触发弹窗后面的信息流，有什么方式能解决吗？

**Comment by gstory0404** [comment]
@yingmiaohuangg 提供了isUserInteractionEnabled参数来控制是否触发点击事件，当上层有弹窗等时改为false来屏蔽穿透问题
```dart
//是否启用点击 仅ios生效 默认启用
isUserInteractionEnabled: true,
```
