### ISSUE TITLE
 flutter_unionad is not init, please check., null, java.lang.RuntimeException: flutter_unionad is not init, please check.

### ISSUE THREAD

**Issue by lude1994** [gstory0404/flutter_unionad#78]
E/flutter ( 5511): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, flutter_unionad is not init, please check., null, java.lang.RuntimeException: flutter_unionad is not init, please check.

Create initializer failed: com.bytedance.sdk.openadsdk.api.plugin.c: dlopen failed: library "libpangleflipped.so" not found
E/初始化( 6006): 失败 4201  No initializer

**Comment by gstory0404** [comment]
加载任何广告前 必须完成初始化

**Comment by gstory0404** [comment]
更新最新插件试试 @lude1994
