### ISSUE TITLE
FlutterUnionad.nativeAdView 对应的穿山甲代码位类型是： draw信息流 还是 信息流

### ISSUE THREAD

**Issue by wengxianxun** [gstory0404/flutter_unionad#82]
FlutterUnionad.nativeAdView 对应的穿山甲代码位类型是： draw信息流 还是 信息流

**Comment by wengxianxun** [comment]
I/flutter (19554): 信息流广告失败 reason: 0  message: 两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8


我请求信息流提示这个错误

**Comment by gstory0404** [comment]
信息流

**Comment by gstory0404** [comment]
升级最新版本插件试一下 @wengxianxun
