### ISSUE TITLE
在IOS会出现穿透现象

### ISSUE THREAD

**Issue by MrRoboots** [gstory0404/flutter_unionad#84]
[图](https://i.328888.xyz/img/2022/12/02/ioePZ.jpeg)

**Comment by gstory0404** [comment]
@MrRoboots 插件版本多少，banner广告吗

**Comment by zeewell** [comment]
Banner广告是会穿透，正想提issue，看已经有了。@gstory0404

**Comment by gstory0404** [comment]
下载demo测试一下 @zeewell @MrRoboots ，广告悬浮在widget之上没有复现，点击穿透需要设置isUserInteractionEnabled开管理是否广告可点击

**Comment by zeewell** [comment]
使用 GTAds 插件接入，最新版本，至少在穿山甲的广告会有这个问题。其他没有测试。

**Comment by zeewell** [comment]
@gstory0404 刚看了楼主的图，这种情况我没出现过～～我出现的问题是点击有穿透。

**Comment by gstory0404** [comment]
@zeewell 单独使用可以通过isUserInteractionEnabled来控制 是否点来处理穿透问题，GTAds的话暂时先关闭穿山甲ios banner广告位，我这边处理下 后面更新个版本

**Comment by zeewell** [comment]
插件接入优量汇也有点小问题，App的页面好像没有显示出来。但日志里已经提示成功

```
-[TLogUtil print:]
 请求广告条数据成功后调用
flutter: Banner显示 {alias: ylh, androidId: xxxxxxxx, iosId: xxxxxxxx, probability: 10}
```

最近时间较忙，还没仔细测试，不确定这个问题的复现概率。初步看好像比较高。

**Comment by MrRoboots** [comment]
@gstory0404 版本是1.3.15 只是ios存在 ios版本是16

**Comment by gstory0404** [comment]
> @gstory0404 版本是1.3.15 只是ios存在 ios版本是16

方便的话 更新到最新的看下

**Comment by gstory0404** [comment]
> @gstory0404 插件接入优量汇的Banner也有点小问题，App页面只空出来了广告的占位，但广告内容并没有显示出来。
> 
> 不过日志里已经提示成功：
> 
> ```
> -[TLogUtil print:]
>  请求广告条数据成功后调用
> flutter: Banner显示 {alias: ylh, androidId: xxxxxxxx, iosId: xxxxxxxx, probability: 10}
> ```
> 
> 最近时间较忙，还没仔细测试，不确定这个问题的复现概率。初步看好像比较高。

不显示复现频率高吗

**Comment by zeewell** [comment]
@gstory0404 我在优量汇插件项目下重新开了个issue，毕竟是不同的项目

https://github.com/gstory0404/flutter_tencentad/issues/24#issue-1478524941

**Comment by gstory0404** [comment]
@zeewell 已更新修复
