### ISSUE TITLE
自己写的插件无广告问题

### ISSUE THREAD

**Issue by lqxue** [gstory0404/flutter_unionad#86]
自己按照穿山甲官网集成的广告,看几遍就提示下面内容:

信息流广告拉去失败 20001 reason: 228 message: 没有合适的广告返回而导致的请求没有填充，偶尔出现属于正常情况。如果出现情况较多或者必现的话，请先检查一下广告尺寸是否填写正确，是否有使用模拟器测试广告，单个设备是否一天请求了大量广告但没有展示或者展示数极低等。排查以上问题依然没有结论可以联系技术支持同学或者提交工单（包含代码位和出现概率以及请求时间）相关同学查明后会做出回复。

但是flutter_unionad 的demo我重复看了好多次都没有提示  广告  没有的情况

您能帮我解释一下为什么吗

**Comment by gstory0404** [comment]
广告位是模版渲染 查看下 @lqxue
