### ISSUE TITLE
Android激励视频调用loadRewardVideoAd后有时不会触发onReady

### ISSUE THREAD

**Issue by shenjingfs** [gstory0404/flutter_unionad#88]
调用FlutterUnionad.loadRewardVideoAd日志：
```E/RewardVideoAd(16365): rewardVideoAd loaded 广告类型：普通激励视频，type=0```
但是Flutter侧的onReady长时间没有触发。
在这之后调用FlutterUnionad.showRewardVideoAd():
```
E/RewardVideoAd(16365): rewardVideoAd show
E/RewardVideoAd(16365): rewardVideoAd video cached
E/RewardVideoAd(16365): rewardVideoAd video cached2
```
此时onReady触发

代码中 onReady 是由 RewardVideoAd.kt 中 onRewardVideoCached 而不是 onRewardVideoAdLoad触发，虽然穿山甲官网写着：
```注：为保证广告视频播放的流畅建议在onRewardVideoCached回调加载完毕后，再在主线程中调用showRewardVideoAd方法进行广告的展示。 展示广告完毕之后及时把广告对象置为null```
但是如果在调用加载后不一定能触发cached的话(不知道是不是我的配置有问题)，onReady就不会触发，这样Flutter侧不知道是否广告加载完成，会影响后续showAd逻辑。

Flutter: 3.3.8
flutter_unionad: 1.3.16
穿山甲管理页应用状态：测试中

**Comment by gstory0404** [comment]
未能复现，测试每次均能触发onReady。
提供预加载方案，所以在onRewardVideoCached中回调。
尝试demo能否复现 @shenjingfs

**Comment by shenjingfs** [comment]
demo测试了几次无法复现。
但是自己的应用还是有时候会这样，应用卸载重装后，一开始正常但是后面又有时会无法触发onReady。这个下周我再进一步测试一下，看看怎么比较能稳定的复现。
onRewardVideoAdLoad 这里是否能添加一个比如叫做 onAdLoad 的事件发送给Flutter侧

**Comment by shenjingfs** [comment]
@gstory0404
demo一直无法复现，自己的APP前天还可以复现，今天也无法复现了。

记录下可能的原因：
1.  昨天下午穿山甲Android端过审了，"应用状态"之前是测试中，而现在是正式运行中。（但是把激励广告的"代码位状态"切换成测试中，也无法复现，所以应该不是这个问题）
2.  之前未正确配置 Android限制HTTP明文流量的（但是今天即使把"android:networkSecurityConfig"移除后，也不能复现，onReady能触发，只是广告的视频加载不出来）

感觉有点玄学，完全定位不到问题出在哪里。


我现在的代码中有个类似adLoading的标志，adLoading在加载方法调用后设为true，在广告加载成功或失败后设为false，如果用户在 adLoading == true 时再次点击了看广告的按钮，那么会提示用户"广告加载中，请稍等"。如果有用户偶然的触发了上面这个问题，那么adLoading一直为true，他就一直看不了广告。代码大致上是这样：
```
Future<void> watchRewardedAd(String unitId) async {
  if (!adLoaded) {
    if (adLoading) {
      showToast('广告加载中，请稍等');
      return;
    }
    bool success = await _loadRewardedVideoAd(unitId: unitId, preload: false);
    if (!success) {
      showToast('广告加载失败');
      return;
    }
  }

  bool rewarded = await _showRewardedVideoAd();
  if (rewarded) {
    // 获取奖励
  }
}
```
我看插件的代码中iOS的onReady是在 nativeExpressRewardedVideoAdDidLoad 中触发，而穿山甲文档中：
```
nativeExpressRewardedVideoAdDidLoad: 回调进入证明广告物料已成功加载。
nativeExpressRewardedVideoAdDidDownLoadVideo: 建议在此回调方法中进行广告的展示操作，可保证播放流畅和展示流畅，用户体验更好。
```
那么 nativeExpressRewardedVideoAdDidLoad 应该是对应的Android的 onRewardVideoAdLoad 吧。这样的话iOS侧并没有等待视频缓存完后，就触发了onReady。

我的建议是 onRewardVideoAdLoad 和 onRewardVideoCached 分开发送两个事件到Flutter侧。
1. 这样我只要在onRewardVideoAdLoad中发送的事件里可以把adLoading设为false，adLoaded设为true，即使触发了上述的问题，用户还是可以正常看广告（当然比起缓存完之后加载，可能会有卡顿，不过实际测试下来，基本不会）。
2. 而对于有的开发者想在缓存完再播放广告，也可以和之前一样通过onRewardVideoCached发送的事件再行处理

**Comment by gstory0404** [comment]
@shenjingfs 发布[v1.3.19](https://github.com/gstory0404/flutter_unionad/blob/master/CHANGELOG.md)

**Comment by shenjingfs** [comment]
好的，谢谢大佬
