### ISSUE TITLE
安卓编译报错

### ISSUE THREAD

**Issue by malegedandan** [gstory0404/flutter_unionad#89]
1.3.18和1.3.17都会有这个错误
1.3.16可以正常运行

错误信息：
/Users/mac/Desktop/tiktoktool/android/app/src/debug/AndroidManifest.xml:84:52-261 Error:
	Attribute meta-data#ZEUS_PLUGIN_LIVE@value value=({                 apiVersionCode:2050,                 packageName:com.byted.live.lite,                 minPluginVersion:205000,                 maxPluginVersion:209999,                 appKey:'9f64a31d9d0456d845733718c4c6934d',                 appSecretKey:'eb7fc60ac5ed4708e13d9c7f8e4096a7',                 isSupportLibIsolate:true,                 internalPath:'plugins/zeusliveplugin.apk',                 internalVersionCode:5,                 signature:'MIIDSTCCAjGgAwIBAgIEaLy5tzANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwIxMTEMMAoGA1UECBMDMTExMQ4wDAYDVQQHEwUxMTExMTEMMAoGA1UEChMDMTExMQwwCgYDVQQLEwMxMTExDDAKBgNVBAMTAzExMTAeFw0yMDEyMDMxMjQyMTJaFw00NTExMjcxMjQyMTJaMFUxCzAJBgNVBAYTAjExMQwwCgYDVQQIEwMxMTExDjAMBgNVBAcTBTExMTExMQwwCgYDVQQKEwMxMTExDDAKBgNVBAsTAzExMTEMMAoGA1UEAxMDMTExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA45E52YdkJm4gPCXZq7KDoM1h6pgSswllC/CwDOmh8pDGvX4ROaYP1vr2biRlXMHg7G0iXpxWVdlTtx+4QFd3dC+cGJQk0f6apGo2n2RpMA0zIsSf0VO1a3GjWLei5INo+4RDdciqJ4jfsoqBIjZETRkky+UU4eO/oyrAwOu4KdMln3Bg3u7eHWU4kMFrXxrRruT3Q/9gzlO90yQa0CZPWVDrk6cGJtJwJGhWm+62S3U8D26HE++eGP7ve83QBDGtKqx7HpCAFWUiYBgXGq12H0amQDkKcPcr/EFCaBlombSgkN0t6zBX80m+wcUPC75IBTmMV/DT2dXcgjZ2I1JSCQIDAQABoyEwHzAdBgNVHQ4EFgQUPDyIeKI0KhZFPHyn36gMMIYrpukwDQYJKoZIhvcNAQELBQADggEBAHkl0DoCRwn+XKsDJE+wGMpBBqUDzL6DSOnJx4SNqb7YZZU0ThcDK7jY4If3QRkvMio6ODrVZc2U/m/Tc3VeMk5h2W2UZRUWHNH3k9Xe0720uL20ZeH2Y6IG4L5HG8kIbTbFtX3gJpPG/xAcez+CzyCFLWQAZt1N+csG0syWkXJ0Nryq8VrgSCyCXD1KzFxrOe+65wtu50Vi68Vlbk7BZe/G8Qm0RhKmxq5BPMBJ4uY3be+03Ba5qC//o1XQHOEAjrJKXcN5wqHdFZTkmuxVyIPogZOzx4JlNl0zOrYGDJxp7aZfKF9FkXQyF7x0Ns3mZEtjx/+flXRzAAU9MDhPr/0='             }) from [:open_ad_sdk_5.0.0.1:] AndroidManifest.xml:84:52-261
	is also present at [com.pangle.cn:partner-live-sdk:2.0.5.0-tob-154732232] AndroidManifest.xml:15:13-1673 value=({                 apiVersionCode:2050,                 packageName:com.byted.live.lite,                 minPluginVersion:205000,                 maxPluginVersion:205999,                 appKey:'9f64a31d9d0456d845733718c4c6934d',                 appSecretKey:'eb7fc60ac5ed4708e13d9c7f8e4096a7',                 isSupportLibIsolate:true,                 internalPath:'plugins/zeusliveplugin.apk',                 internalVersionCode:5,                 signature:'MIIDSTCCAjGgAwIBAgIEaLy5tzANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwIxMTEMMAoGA1UECBMDMTExMQ4wDAYDVQQHEwUxMTExMTEMMAoGA1UEChMDMTExMQwwCgYDVQQLEwMxMTExDDAKBgNVBAMTAzExMTAeFw0yMDEyMDMxMjQyMTJaFw00NTExMjcxMjQyMTJaMFUxCzAJBgNVBAYTAjExMQwwCgYDVQQIEwMxMTExDjAMBgNVBAcTBTExMTExMQwwCgYDVQQKEwMxMTExDDAKBgNVBAsTAzExMTEMMAoGA1UEAxMDMTExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA45E52YdkJm4gPCXZq7KDoM1h6pgSswllC/CwDOmh8pDGvX4ROaYP1vr2biRlXMHg7G0iXpxWVdlTtx+4QFd3dC+cGJQk0f6apGo2n2RpMA0zIsSf0VO1a3GjWLei5INo+4RDdciqJ4jfsoqBIjZETRkky+UU4eO/oyrAwOu4KdMln3Bg3u7eHWU4kMFrXxrRruT3Q/9gzlO90yQa0CZPWVDrk6cGJtJwJGhWm+62S3U8D26HE++eGP7ve83QBDGtKqx7HpCAFWUiYBgXGq12H0amQDkKcPcr/EFCaBlombSgkN0t6zBX80m+wcUPC75IBTmMV/DT2dXcgjZ2I1JSCQIDAQABoyEwHzAdBgNVHQ4EFgQUPDyIeKI0KhZFPHyn36gMMIYrpukwDQYJKoZIhvcNAQELBQADggEBAHkl0DoCRwn+XKsDJE+wGMpBBqUDzL6DSOnJx4SNqb7YZZU0ThcDK7jY4If3QRkvMio6ODrVZc2U/m/Tc3VeMk5h2W2UZRUWHNH3k9Xe0720uL20ZeH2Y6IG4L5HG8kIbTbFtX3gJpPG/xAcez+CzyCFLWQAZt1N+csG0syWkXJ0Nryq8VrgSCyCXD1KzFxrOe+65wtu50Vi68Vlbk7BZe/G8Qm0RhKmxq5BPMBJ4uY3be+03Ba5qC//o1XQHOEAjrJKXcN5wqHdFZTkmuxVyIPogZOzx4JlNl0zOrYGDJxp7aZfKF9FkXQyF7x0Ns3mZEtjx/+flXRzAAU9MDhPr/0='             }).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:84:9-1674 to override.

FAILURE: Build failed with an exception.

感谢大佬帮忙解决，谢谢！

**Comment by gstory0404** [comment]
```
Suggestion: add 'tools:replace="android:value"' to element at AndroidManifest.xml:84:9-1674 to override.
```
添加这个tools:replace="android:value 到AndroidManifest.xml文件中Application下 @malegedandan

**Comment by malegedandan** [comment]
<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:value"
        >
如上配置，还是报错
错误信息：
/Users/mac/Desktop/tiktoktool/android/app/src/main/AndroidManifest.xml:46:5-120:19 Error:
	tools:replace specified at line:46 for attribute android:value, but no new value specified
/Users/mac/Desktop/tiktoktool/android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by malegedandan** [comment]
> 

@gstory0404

**Comment by gstory0404** [comment]
怎么添加的 发出来 @malegedandan

**Comment by malegedandan** [comment]
> 如上配置，还是报错

<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:value"
        >
@gstory0404

**Comment by malegedandan** [comment]
////
<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:label"
        >
////

**Comment by malegedandan** [comment]
application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:label"

**Comment by malegedandan** [comment]
application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:label"
        @gstory0404 
这个配置，前面发了，没显示出来

**Comment by malegedandan** [comment]
<application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:value"
        >
@gstory0404 
这个配置，前面发了，没显示出来

**Comment by malegedandan** [comment]
application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:value"
     
这个配置，前面发了，没显示出来 @gstory0404

**Comment by gstory0404** [comment]
在AndroidManifest.xml:84行添加tools:replace="android:value"，修改之前 @malegedandan

**Comment by malegedandan** [comment]
> 在AndroidManifest.xml:84行添加tools:replace="android:value"，修改之前 @malegedandan

application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:replace="android:label"

**Comment by malegedandan** [comment]
@gstory0404 

> 在AndroidManifest.xml:84行添加tools:replace="android:value"，修改之前 @malegedandan

application
android:icon="@mipmap/ic_launcher"
android:label="@string/app_name"
android:requestLegacyExternalStorage="true"
android:usesCleartextTraffic="true"
tools:replace="android:label"

**Comment by gstory0404** [comment]
之前的84行事<Application>吗

**Comment by malegedandan** [comment]
> 之前的84行事吗

1.3.16及以前的版本不会报这个错误

**Comment by gstory0404** [comment]
之前的84行代码是啥 @malegedandan

**Comment by malegedandan** [comment]
![image](https://user-images.githubusercontent.com/17779916/211236941-36605dd0-7814-46ab-bf07-cd27fab2a5fb.png)



> 之前的84行代码是啥 @malegedandan

**Comment by malegedandan** [comment]
![image](https://user-images.githubusercontent.com/17779916/211236991-5079a9cb-3c10-4784-9e62-d527980dad76.png)

**Comment by gstory0404** [comment]
tools:replace="android:value" 添加在修改之前的84行，不要在application中添加

**Comment by malegedandan** [comment]
![image](https://user-images.githubusercontent.com/17779916/211238068-a084409a-7b2c-4331-83dd-efa31e4d3f38.png)
是这样吗，不太懂

**Comment by gstory0404** [comment]
提示让你加哪里就加哪里
