### ISSUE TITLE
开屏广告不显示可能是什么问题，其他类型配置的广告已经正常显示

### ISSUE THREAD

**Issue by zjypp** [gstory0404/flutter_unionad#93]
版本是：  flutter_unionad: ^1.3.19
其他类型的广告可以显示
执行这个方法以后，回调方法没有一个执行的，也没有看到报错信息；

FlutterUnionad.splashAdView(
      //是否使用个性化模版  设定widget宽高
      //mIsExpress: true,
      //android 开屏广告广告id 必填
      androidCodeId: "000000",
      //ios 开屏广告广告id 必填
      iosCodeId: "",
      //是否支持 DeepLink 选填
      //supportDeepLink: true,
      // 期望view 宽度 dp 选填 mIsExpress=true必填
     expressViewWidth: 750,
      //期望view高度 dp 选填 mIsExpress=true必填
      expressViewHeight: 1200,
      //控制下载APP前是否弹出二次确认弹窗
      downloadType: FlutterUnionadDownLoadType.DOWNLOAD_TYPE_POPUP,
      //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
      adLoadType: FlutterUnionadLoadType.LOAD,
      //是否影藏跳过按钮(当影藏的时候显示自定义跳过按钮) 默认显示
      hideSkip: false,
      callBack: FlutterUnionadSplashCallBack(
        onShow: () {
          print("开屏广告显示");
        },
        onClick: () {
          print("开屏广告点击");
          //Navigator.pop(context);
        },
        onFail: (error) {
          print("开屏广告失败 $error");
        },
        onFinish: () {
          print("开屏广告倒计时结束");
          //Navigator.pop(context);
        },
        onSkip: () {
          print("开屏广告跳过");
          //Navigator.pop(context);
        },
        onTimeOut: () {
          print("开屏广告超时");
        },
      ),
    );

**Comment by gstory0404** [comment]
android还是ios 系统版本号多少 @zjypp

**Comment by gstory0404** [comment]
试下更新1.3.20 还有没有异常
