### ISSUE TITLE
开屏广告什么时候调用呢？有要求吗？为什么开屏广告一次都不能成功，也没有任何callback事件的响应

### ISSUE THREAD

**Issue by zjypp** [gstory0404/flutter_unionad#96]
最新的版本  flutter_unionad: ^1.3.20

在初始化方法完成以后，我调用的开屏方法。也没有任何callback事件的响应

static void startScreenAd(var adId){
    print("toutiao start screen to begin...");
    FlutterUnionad.splashAdView(
      //是否使用个性化模版  设定widget宽高
      //mIsExpress: true,
      //android 开屏广告广告id 必填
      androidCodeId: adId,
      //ios 开屏广告广告id 必填
      iosCodeId: "",
      //是否支持 DeepLink 选填
      //supportDeepLink: true,
      // 期望view 宽度 dp 选填 mIsExpress=true必填
     expressViewWidth: 750,
      //期望view高度 dp 选填 mIsExpress=true必填
      expressViewHeight: 1200,
      //控制下载APP前是否弹出二次确认弹窗
      downloadType: FlutterUnionadDownLoadType.DOWNLOAD_TYPE_POPUP,
      //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
      adLoadType: FlutterUnionadLoadType.LOAD,
      //是否影藏跳过按钮(当影藏的时候显示自定义跳过按钮) 默认显示
      hideSkip: false,
      callBack: FlutterUnionadSplashCallBack(
        onShow: () {
          print("开屏广告显示");
        },
        onClick: () {
          print("开屏广告点击");
          //Navigator.pop(context);
        },
        onFail: (error) {
          print("开屏广告失败 $error");
        },
        onFinish: () {
          print("开屏广告倒计时结束");
          //Navigator.pop(context);
        },
        onSkip: () {
          print("开屏广告跳过");
          //Navigator.pop(context);
        },
        onTimeOut: () {
          print("开屏广告超时");
        },
      ),
    );
  }

**Comment by zjypp** [comment]
> static void startScreenAd(var adId){
    print("toutiao start screen to begin...");
    FlutterUnionad.splashAdView(
      //是否使用个性化模版  设定widget宽高
      //mIsExpress: true,
      //android 开屏广告广告id 必填
      androidCodeId: adId,
      //ios 开屏广告广告id 必填
      iosCodeId: "",
      //是否支持 DeepLink 选填
      //supportDeepLink: true,
      // 期望view 宽度 dp 选填 mIsExpress=true必填
     expressViewWidth: 750,
      //期望view高度 dp 选填 mIsExpress=true必填
      expressViewHeight: 1200,
      //控制下载APP前是否弹出二次确认弹窗
      downloadType: FlutterUnionadDownLoadType.DOWNLOAD_TYPE_POPUP,
      //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
      adLoadType: FlutterUnionadLoadType.LOAD,
      //是否影藏跳过按钮(当影藏的时候显示自定义跳过按钮) 默认显示
      hideSkip: false,
      callBack: FlutterUnionadSplashCallBack(
        onShow: () {
          print("开屏广告显示");
        },
        onClick: () {
          print("开屏广告点击");
          //Navigator.pop(context);
        },
        onFail: (error) {
          print("开屏广告失败 $error");
        },
        onFinish: () {
          print("开屏广告倒计时结束");
          //Navigator.pop(context);
        },
        onSkip: () {
          print("开屏广告跳过");
          //Navigator.pop(context);
        },
        onTimeOut: () {
          print("开屏广告超时");
        },
      ),
    );
  }

**Comment by zjypp** [comment]
`static void startScreenAd(var adId){
    print("toutiao start screen to begin...");
    FlutterUnionad.splashAdView(
      //是否使用个性化模版  设定widget宽高
      //mIsExpress: true,
      //android 开屏广告广告id 必填
      androidCodeId: adId,
      //ios 开屏广告广告id 必填
      iosCodeId: "",
      //是否支持 DeepLink 选填
      //supportDeepLink: true,
      // 期望view 宽度 dp 选填 mIsExpress=true必填
     expressViewWidth: 750,
      //期望view高度 dp 选填 mIsExpress=true必填
      expressViewHeight: 1200,
      //控制下载APP前是否弹出二次确认弹窗
      downloadType: FlutterUnionadDownLoadType.DOWNLOAD_TYPE_POPUP,
      //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
      adLoadType: FlutterUnionadLoadType.LOAD,
      //是否影藏跳过按钮(当影藏的时候显示自定义跳过按钮) 默认显示
      hideSkip: false,
      callBack: FlutterUnionadSplashCallBack(
        onShow: () {
          print("开屏广告显示");
        },
        onClick: () {
          print("开屏广告点击");
          //Navigator.pop(context);
        },
        onFail: (error) {
          print("开屏广告失败 $error");
        },
        onFinish: () {
          print("开屏广告倒计时结束");
          //Navigator.pop(context);
        },
        onSkip: () {
          print("开屏广告跳过");
          //Navigator.pop(context);
        },
        onTimeOut: () {
          print("开屏广告超时");
        },
      ),
    );
  }`

**Comment by gstory0404** [comment]
初始化是否成功

**Comment by zjypp** [comment]
我是没弄成功的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月29日 17:00 |
| 收件人 | ***@***.***> |
| 抄送至 | Jason ***@***.***>***@***.***> |
| 主题 | Re: [gstory0404/flutter_unionad] 开屏广告什么时候调用呢？有要求吗？为什么开屏广告一次都不能成功，也没有任何callback事件的响应 (Issue #96) |

image.png (view on web) release打包之后开屏广告就无法展示了，偶尔又会展示

**Comment by sineom-1** [comment]
找到原因了，由于初始化是异步导致的

**Comment by zjypp** [comment]
在main中写？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月29日 17:56 |
| 收件人 | ***@***.***> |
| 抄送至 | Jason ***@***.***>***@***.***> |
| 主题 | Re: [gstory0404/flutter_unionad] 开屏广告什么时候调用呢？有要求吗？为什么开屏广告一次都不能成功，也没有任何callback事件的响应 (Issue #96) |

找到原因了，由于初始化是异步导致的

**Comment by gstory0404** [comment]
需要在register 返回true后调用 否则无法加载广告
