### ISSUE TITLE
初始化提示 library "libpangleflipped.so" not found

### ISSUE THREAD

**Issue by xinggg22** [gstory0404/flutter_unionad#98]
Create initializer failed: com.bytedance.sdk.openadsdk.api.plugin.z: dlopen failed: library "libpangleflipped.so" not found

**Comment by gstory0404** [comment]
用真机

> Create initializer failed: com.bytedance.sdk.openadsdk.api.plugin.z: dlopen failed: library "libpangleflipped.so" not found

**Comment by xinggg22** [comment]
@gstory0404 模拟机怎么解决呢？

**Comment by gstory0404** [comment]
> @gstory0404 模拟机怎么解决呢？

官方不支持x86模拟器，如果需要的话 找官方要，自己替换

**Comment by xinggg22** [comment]
@gstory0404 是值穿山甲不支持x86模拟器吗？

**Comment by gstory0404** [comment]
> @gstory0404 是值穿山甲不支持x86模拟器吗？

对，官方sdk不支持，与插件无关

**Comment by xinggg22** [comment]
@gstory0404 感谢！看来只能真机调试了。

**Comment by xinggg22** [comment]
官方sdk不支持，与插件无关，只能真机调试。
