### ISSUE TITLE
调用全屏广告FlutterUnionad.loadFullScreenVideoAdInteraction无法显示

### ISSUE THREAD

**Issue by xinggg22** [gstory0404/flutter_unionad#99]
FlutterUnionad.loadFullScreenVideoAdInteraction(
                          //android 全屏广告id 必填
                          androidCodeId:fullScreenVideoId2,
                          //ios 全屏广告id 必填
                          iosCodeId: fullScreenVideoId2,
                          //是否支持 DeepLink 选填
                          supportDeepLink: true,
                          //视屏方向 选填
                          orientation: FlutterUnionadOrientation.VERTICAL,
                          //控制下载APP前是否弹出二次确认弹窗
                          downloadType:
                              FlutterUnionadDownLoadType.DOWNLOAD_TYPE_POPUP,
                          //用于标注此次的广告请求用途为预加载（当做缓存）还是实时加载，
                          adLoadType: FlutterUnionadLoadType.PRELOAD,
                        );

显示：
getServiceManager:Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference

**Comment by gstory0404** [comment]
@xinggg22 模拟器？

**Comment by xinggg22** [comment]
@gstory0404 真机

**Comment by gstory0404** [comment]
@xinggg22 错误貌似不是这个日志 查看所有日志
